general:
  seed: 42
  num_workers: 4
experiment:
  name: "CNN_Hyperparameter_Tuning_CIFAR100"
  description: "CNN hyperparameter tuning on the CIFAR100 dataset"
  save_dir: "./results/hyperparameter_tuning/cnn"
  log_dir: "./logs/experiment_logs/hyperparameter_tuning/cnn"
  tensorboard_log_dir: "./logs/tensorboard/hyperparameter_tuning/cnn"
  checkpoints_dir: "checkpoints/hyperparameter_tuning/cnn"
  resume_checkpoint: null
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_to_file: True
  log_to_console: True
monitoring:
  tensorboard: True
checkpointing:
  save_best_only: True
  monitor_metric: "val_loss"
  max_checkpoints: 5
early_stopping:
  enabled: True
  monitor: "val_loss"
  patience: 5
  min_delta: 0.001
hyperparameter_optimization:
  n_trials: 100
  pruner: "SuccessiveHalvingPruner"
  direction: "minimize"
evaluation:
  metrics: ["accuracy", "precision", "recall", "f1"]
  batch_size: 32
  num_workers: 4
misc:
  debug: False
  use_mixed_precision: True
  deterministic: False
  additional_config: "path_to_additional_config.yaml"
  smaller_dataset: False
  num_epochs_debug: 5
  profiler_enabled: False
